#!/usr/bin/env bash
# ==============================================================================
#  AHPC Laravel Deployment Script
#  Handles: Nginx config, PHP-FPM, folder permissions, hostname, mDNS, DNS
#  Target:  Ubuntu Server — direct access (no SSH/FTP)
#  Run as:  sudo bash deploy-ahpc.sh
# ==============================================================================

set -euo pipefail
IFS=$'\n\t'

# ── Colours ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC}   $*"; }
ok()      { echo -e "${GREEN}[OK]${NC}     $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}   $*"; }
die()     { echo -e "${RED}[FATAL]${NC}  $*" >&2; exit 1; }
section() { echo -e "\n${BOLD}${CYAN}┌─ $* ${NC}"; }

# ── Config ─────────────────────────────────────────────────────────────────────
APP_DIR="/var/www/html/ahpc"
APP_HOSTNAME="ahpc"
NGINX_AVAILABLE="/etc/nginx/sites-available/ahpc"
NGINX_ENABLED="/etc/nginx/sites-enabled/ahpc"
WEB_USER="www-data"

# ==============================================================================
#  0. PRE-FLIGHT CHECKS
# ==============================================================================
section "Pre-flight checks"

[[ $EUID -ne 0 ]] && die "Must run as root. Use: sudo bash $0"

[[ -d "$APP_DIR" ]]           || die "Project directory not found: $APP_DIR"
[[ -f "$APP_DIR/artisan" ]]   || die "Laravel artisan missing. Is the project correctly cloned at $APP_DIR?"
command -v nginx &>/dev/null  || die "nginx not installed. Run: apt install nginx"
command -v php   &>/dev/null  || die "php not installed."

ok "All pre-flight checks passed"

# ==============================================================================
#  1. DETECT PHP VERSION & FPM SOCKET
# ==============================================================================
section "Detecting PHP-FPM"

PHP_VER=$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null) \
    || die "Cannot determine PHP version"
info "PHP version: $PHP_VER"

FPM_SERVICE="php${PHP_VER}-fpm"

# Ensure PHP-FPM is running before looking for socket
if ! systemctl is-active --quiet "$FPM_SERVICE" 2>/dev/null; then
    info "Starting $FPM_SERVICE..."
    systemctl enable --now "$FPM_SERVICE" \
        || die "$FPM_SERVICE could not start. Check: systemctl status $FPM_SERVICE"
    sleep 1
fi

# Locate the socket file
FPM_SOCK=""
CANDIDATE_SOCKS=(
    "/run/php/php${PHP_VER}-fpm.sock"
    "/var/run/php/php${PHP_VER}-fpm.sock"
    "/run/php-fpm/www.sock"
)
for sock in "${CANDIDATE_SOCKS[@]}"; do
    if [[ -S "$sock" ]]; then
        FPM_SOCK="$sock"
        break
    fi
done

[[ -n "$FPM_SOCK" ]] \
    || die "PHP-FPM socket not found. Tried: ${CANDIDATE_SOCKS[*]}\nCheck: systemctl status $FPM_SERVICE"

ok "PHP-FPM socket: $FPM_SOCK"

# ==============================================================================
#  2. STOP & DISABLE APACHE
# ==============================================================================
section "Disabling Apache (freeing port 80)"

if systemctl is-active --quiet apache2 2>/dev/null; then
    systemctl stop apache2
    ok "apache2 stopped"
else
    info "apache2 was not running"
fi

if systemctl is-enabled --quiet apache2 2>/dev/null; then
    systemctl disable apache2
    ok "apache2 disabled (will not start on boot)"
else
    info "apache2 was already disabled"
fi

# ==============================================================================
#  3. WRITE NGINX SITE CONFIGURATION
# ==============================================================================
section "Writing Nginx configuration → $NGINX_AVAILABLE"

cat > "$NGINX_AVAILABLE" << NGINXEOF
##
##  AHPC – Laravel Application
##  /etc/nginx/sites-available/ahpc
##  Generated by deploy-ahpc.sh
##

server {
    listen 80;
    listen [::]:80;

    server_name ${APP_HOSTNAME}.internal ${APP_HOSTNAME}.local ${APP_HOSTNAME};

    root ${APP_DIR}/public;
    index index.php index.html;

    charset utf-8;

    # ── Logging ────────────────────────────────────────────────────────────────
    access_log  /var/log/nginx/ahpc.access.log;
    error_log   /var/log/nginx/ahpc.error.log warn;

    # ── Upload limit ───────────────────────────────────────────────────────────
    client_max_body_size 64M;

    # ── Laravel front-controller ───────────────────────────────────────────────
    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    # ── Static assets – long-lived cache ──────────────────────────────────────
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|webp|woff|woff2|ttf|eot|otf|map)\$ {
        expires        30d;
        access_log     off;
        add_header     Cache-Control "public, immutable";
        try_files      \$uri =404;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # ── PHP-FPM ────────────────────────────────────────────────────────────────
    location ~ \.php\$ {
        try_files       \$uri =404;
        fastcgi_pass    unix:${FPM_SOCK};
        fastcgi_index   index.php;
        fastcgi_param   SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include         fastcgi_params;
        fastcgi_hide_header X-Powered-By;

        # Timeouts – generous for exam/PDF generation
        fastcgi_read_timeout    300;
        fastcgi_send_timeout    300;
        fastcgi_connect_timeout 60;

        # Buffer tuning
        fastcgi_buffer_size     128k;
        fastcgi_buffers         8 256k;
        fastcgi_busy_buffers_size 256k;
    }

    # ── Block dot-files (except Let's Encrypt well-known) ─────────────────────
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # ── Block direct access to sensitive Laravel files ─────────────────────────
    location ~* (\.env|composer\.(json|lock)|package\.json|webpack\.mix\.js|artisan)\$ {
        deny all;
        return 404;
    }

    # ── Gzip ──────────────────────────────────────────────────────────────────
    gzip             on;
    gzip_comp_level  5;
    gzip_min_length  256;
    gzip_proxied     any;
    gzip_types
        text/plain text/css text/xml text/javascript
        application/javascript application/json application/xml
        application/x-font-ttf font/opentype image/svg+xml;
}
NGINXEOF

ok "Nginx config written"

# ==============================================================================
#  4. ENABLE SITE — SYMLINK & REMOVE DEFAULT
# ==============================================================================
section "Enabling Nginx site"

# Remove stale symlink if it points somewhere wrong
[[ -L "$NGINX_ENABLED" ]] && rm -f "$NGINX_ENABLED"
ln -s "$NGINX_AVAILABLE" "$NGINX_ENABLED"
ok "Symlinked: $NGINX_ENABLED → $NGINX_AVAILABLE"

# Remove the Nginx default site — it competes on port 80
if [[ -L /etc/nginx/sites-enabled/default ]]; then
    rm -f /etc/nginx/sites-enabled/default
    info "Removed default Nginx site (sites-enabled/default)"
fi

# ==============================================================================
#  5. FOLDER PERMISSIONS
# ==============================================================================
section "Setting folder permissions"

# Full ownership to www-data
chown -R "${WEB_USER}:${WEB_USER}" "$APP_DIR"

# Files: 644, Directories: 755
find "$APP_DIR" -type f -exec chmod 644 {} \;
find "$APP_DIR" -type d -exec chmod 755 {} \;

# Laravel writable directories
chmod -R 775 "$APP_DIR/storage"
chmod -R 775 "$APP_DIR/bootstrap/cache"

# Make artisan executable
chmod +x "$APP_DIR/artisan"

ok "Permissions applied"
info "  Files:                644 (rw-r--r--)"
info "  Directories:          755 (rwxr-xr-x)"
info "  storage/:             775 (rwxrwxr-x) — web-writable"
info "  bootstrap/cache/:     775 (rwxrwxr-x) — web-writable"

# ==============================================================================
#  6. LARAVEL ENVIRONMENT SETUP
# ==============================================================================
section "Laravel environment"

# Create .env from .env.example if missing
if [[ ! -f "$APP_DIR/.env" ]]; then
    if [[ -f "$APP_DIR/.env.example" ]]; then
        cp "$APP_DIR/.env.example" "$APP_DIR/.env"
        chown "${WEB_USER}:${WEB_USER}" "$APP_DIR/.env"
        chmod 640 "$APP_DIR/.env"
        warn ".env created from .env.example — EDIT IT before first use (DB creds, APP_URL, etc.)"
    else
        warn "No .env or .env.example found — create $APP_DIR/.env manually"
    fi
else
    ok ".env exists"
fi

# Generate APP_KEY if blank
if [[ -f "$APP_DIR/.env" ]]; then
    APP_KEY_VAL=$(grep '^APP_KEY=' "$APP_DIR/.env" | cut -d= -f2 | tr -d '[:space:]')
    if [[ -z "$APP_KEY_VAL" ]]; then
        sudo -u "${WEB_USER}" bash -c "cd '${APP_DIR}' && php artisan key:generate --force"
        ok "APP_KEY generated"
    else
        info "APP_KEY already set — skipping"
    fi
fi

# ==============================================================================
#  7. COMPOSER DEPENDENCIES
# ==============================================================================
section "Composer dependencies"

if command -v composer &>/dev/null; then
    if [[ ! -d "$APP_DIR/vendor" ]]; then
        info "Running composer install (production)..."
        sudo -u "${WEB_USER}" composer install \
            --no-dev --optimize-autoloader --no-interaction \
            --working-dir="$APP_DIR"
        ok "composer install complete"
    else
        info "vendor/ already exists — skipping (run composer install manually if needed)"
    fi
else
    warn "composer not in PATH — skipping (install dependencies manually)"
fi

# ==============================================================================
#  8. LARAVEL OPTIMISATION CACHES
# ==============================================================================
section "Laravel optimisation"

cd "$APP_DIR"

# These should not require DB; soft-fail so missing DB doesn't abort script
sudo -u "${WEB_USER}" php artisan config:cache  && ok "config:cache"  || warn "config:cache failed — check .env"
sudo -u "${WEB_USER}" php artisan route:cache   && ok "route:cache"   || warn "route:cache failed"
sudo -u "${WEB_USER}" php artisan view:cache    && ok "view:cache"    || warn "view:cache failed"

# ==============================================================================
#  9. SERVER HOSTNAME
# ==============================================================================
section "Setting server hostname to '$APP_HOSTNAME'"

CURRENT_HOST=$(hostname)
if [[ "$CURRENT_HOST" != "$APP_HOSTNAME" ]]; then
    hostnamectl set-hostname "$APP_HOSTNAME"
    ok "Hostname: $CURRENT_HOST → $APP_HOSTNAME"
else
    info "Hostname already set to '$APP_HOSTNAME'"
fi

# Update /etc/hosts — ensure loopback entries exist for both domains
# Remove any old entries for this hostname first, then re-add cleanly
sed -i "/\s${APP_HOSTNAME}$/d"          /etc/hosts 2>/dev/null || true
sed -i "/\s${APP_HOSTNAME}\s/d"         /etc/hosts 2>/dev/null || true
sed -i "/\s${APP_HOSTNAME}\.local/d"    /etc/hosts 2>/dev/null || true
sed -i "/\s${APP_HOSTNAME}\.internal/d" /etc/hosts 2>/dev/null || true

# Re-add clean entries
{
    echo "127.0.0.1   ${APP_HOSTNAME}.local ${APP_HOSTNAME}.internal ${APP_HOSTNAME}"
    echo "127.0.1.1   ${APP_HOSTNAME}.local ${APP_HOSTNAME}.internal ${APP_HOSTNAME}"
} >> /etc/hosts

ok "/etc/hosts updated"

# ==============================================================================
#  10. mDNS — AVAHI DAEMON (.local auto-discovery)
# ==============================================================================
section "mDNS via avahi-daemon (ahpc.local — zero-config for LAN devices)"

if ! command -v avahi-daemon &>/dev/null; then
    info "Installing avahi-daemon + libnss-mdns..."
    apt-get update -qq
    apt-get install -y avahi-daemon avahi-utils libnss-mdns
fi

# Ensure /etc/nsswitch.conf has mdns4_minimal so local processes resolve .local
if ! grep -q 'mdns4_minimal' /etc/nsswitch.conf; then
    sed -i 's/^hosts:.*/hosts:          files mdns4_minimal [NOTFOUND=return] dns/' /etc/nsswitch.conf
    info "nsswitch.conf updated for mDNS"
fi

# Avahi config — publish hostname, disable wide-area DNS-SD
cat > /etc/avahi/avahi-daemon.conf << 'AVAHIEOF'
[server]
host-name=ahpc
domain-name=local
use-ipv4=yes
use-ipv6=no
allow-interfaces=lo
deny-interfaces=lo
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=yes
publish-domain=yes
AVAHIEOF

systemctl enable --now avahi-daemon
systemctl restart avahi-daemon
ok "avahi-daemon running — ahpc.local resolvable on LAN via mDNS (no client config needed)"

# ==============================================================================
#  11. DNS — DNSMASQ (.internal domain for LAN)
# ==============================================================================
section "LAN DNS via dnsmasq (ahpc.internal — optional, requires client DNS config)"

# Detect server LAN IP
SERVER_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)
[[ -z "$SERVER_IP" ]] && SERVER_IP=$(hostname -I | awk '{print $1}')
info "Detected server LAN IP: $SERVER_IP"

if ! command -v dnsmasq &>/dev/null; then
    info "Installing dnsmasq..."
    apt-get install -y dnsmasq
fi

# ── Fix port 53 conflict: disable systemd-resolved stub listener ──────────────
RESOLVED_CONF="/etc/systemd/resolved.conf"
if [[ -f "$RESOLVED_CONF" ]]; then
    # Disable stub listener so dnsmasq can bind :53
    if grep -q '^#*DNSStubListener' "$RESOLVED_CONF"; then
        sed -i 's/^#*DNSStubListener=.*/DNSStubListener=no/' "$RESOLVED_CONF"
    else
        echo "DNSStubListener=no" >> "$RESOLVED_CONF"
    fi
    systemctl restart systemd-resolved
    sleep 1
    ok "systemd-resolved stub listener disabled"
fi

# Point /etc/resolv.conf at the real (non-stub) systemd-resolved file
# so the system itself still has working upstream DNS
ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
info "resolv.conf → /run/systemd/resolve/resolv.conf (upstream DNS intact)"

# ── Write dnsmasq drop-in for AHPC ───────────────────────────────────────────
mkdir -p /etc/dnsmasq.d
cat > /etc/dnsmasq.d/ahpc.conf << DNSEOF
# ──────────────────────────────────────────────────
#  AHPC Internal DNS — /etc/dnsmasq.d/ahpc.conf
# ──────────────────────────────────────────────────

# Upstream DNS servers
server=1.1.1.1
server=8.8.8.8
server=8.8.4.4

# Resolve ahpc.internal and ahpc.local to this server
address=/${APP_HOSTNAME}.internal/${SERVER_IP}
address=/${APP_HOSTNAME}.local/${SERVER_IP}
address=/${APP_HOSTNAME}/${SERVER_IP}

# Listen on loopback AND LAN interface
listen-address=127.0.0.1,${SERVER_IP}
bind-dynamic

# Don't forward bare hostnames or private IPs upstream
domain-needed
bogus-priv
no-resolv

# Cache 1 hour
cache-size=1000
local-ttl=3600
DNSEOF

# ── Ensure base dnsmasq.conf doesn't block our drop-in ───────────────────────
DNSMASQ_CONF="/etc/dnsmasq.conf"
if ! grep -q "^conf-dir=/etc/dnsmasq.d" "$DNSMASQ_CONF" 2>/dev/null; then
    echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> "$DNSMASQ_CONF"
fi

systemctl enable dnsmasq
systemctl restart dnsmasq
ok "dnsmasq running — serving ${APP_HOSTNAME}.internal → ${SERVER_IP}"

# ==============================================================================
#  12. FIREWALL
# ==============================================================================
section "Firewall rules"

if command -v ufw &>/dev/null && ufw status | grep -q 'Status: active'; then
    ufw allow 80/tcp   comment 'AHPC HTTP'  2>/dev/null
    ufw allow 53/tcp   comment 'AHPC DNS'   2>/dev/null
    ufw allow 53/udp   comment 'AHPC DNS'   2>/dev/null
    ufw allow 5353/udp comment 'AHPC mDNS'  2>/dev/null
    ok "UFW rules added: HTTP (80), DNS (53 tcp/udp), mDNS (5353)"
else
    info "UFW not active — skipping firewall rules"
fi

# ==============================================================================
#  13. TEST & RELOAD NGINX
# ==============================================================================
section "Testing and reloading Nginx"

nginx -t 2>&1 | sed 's/^/  /' || die "Nginx config test failed — review $NGINX_AVAILABLE"
systemctl enable --now nginx
systemctl reload nginx
ok "Nginx reloaded"

# Verify PHP-FPM is still up after all the restarts
systemctl is-active --quiet "$FPM_SERVICE" || {
    systemctl restart "$FPM_SERVICE"
    ok "$FPM_SERVICE restarted"
}

# ==============================================================================
#  14. SMOKE TEST
# ==============================================================================
section "Smoke test"

sleep 1
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1/" \
    -H "Host: ${APP_HOSTNAME}.local" 2>/dev/null || echo "000")

if [[ "$HTTP_CODE" == "200" || "$HTTP_CODE" == "302" ]]; then
    ok "HTTP $HTTP_CODE — application is responding"
elif [[ "$HTTP_CODE" == "500" ]]; then
    warn "HTTP 500 — app is reachable but returned a server error (check .env / DB config)"
else
    warn "HTTP $HTTP_CODE — unexpected response (app may still need .env / DB setup)"
fi

# ==============================================================================
#  15. SUMMARY
# ==============================================================================
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════════╗"
echo -e "║            AHPC Deployment Complete ✓                   ║"
echo -e "╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Application root:${NC}   $APP_DIR"
echo -e "  ${BOLD}Server LAN IP:${NC}      $SERVER_IP"
echo -e "  ${BOLD}PHP version:${NC}        $PHP_VER"
echo -e "  ${BOLD}FPM socket:${NC}         $FPM_SOCK"
echo ""
echo -e "  ${BOLD}${CYAN}Access URLs${NC}"
echo -e "  ┌───────────────────────────────────────────────────────┐"
echo -e "  │  http://ahpc.local           — mDNS  (zero-config)   │"
echo -e "  │  http://ahpc.internal        — DNS   (see below)      │"
echo -e "  │  http://${SERVER_IP}         — by IP (always works)  │"
echo -e "  └───────────────────────────────────────────────────────┘"
echo ""
echo -e "  ${BOLD}${CYAN}How other LAN devices can reach the site${NC}"
echo ""
echo -e "  ${BOLD}Option A — http://ahpc.local  [EASIEST, recommended]${NC}"
echo -e "  Uses mDNS (Avahi/Bonjour). Works automatically on:"
echo -e "    • macOS / iOS (built-in Bonjour)"
echo -e "    • Linux with avahi-daemon / nss-mdns installed"
echo -e "    • Windows 10/11 with iTunes or Bonjour Print Services"
echo -e "    • Android (limited — see Option C)"
echo ""
echo -e "  ${BOLD}Option B — http://ahpc.internal  [DNS-based]${NC}"
echo -e "  Requires client devices to use this server as DNS."
echo -e "  Set DNS server on each device (or via router DHCP) to:"
echo -e "    ${BOLD}${SERVER_IP}${NC}"
echo -e "  Then http://ahpc.internal will resolve everywhere."
echo ""
echo -e "  ${BOLD}Option C — Manual hosts entry  [per device]${NC}"
echo -e "  Add this line to each device's hosts file:"
echo -e "    ${BOLD}${SERVER_IP}   ahpc.internal ahpc.local${NC}"
echo -e "    Windows: C:\\Windows\\System32\\drivers\\etc\\hosts"
echo -e "    Linux/Mac: /etc/hosts"
echo ""
echo -e "  ${BOLD}${CYAN}Recommended next steps${NC}"
echo -e "  ─────────────────────────────────────────────────────────"
echo -e "  1. Edit .env:    nano $APP_DIR/.env"
echo -e "     Set: APP_URL=http://ahpc.local"
echo -e "          DB_HOST, DB_DATABASE, DB_USERNAME, DB_PASSWORD"
echo ""
echo -e "  2. Run migrations:"
echo -e "     cd $APP_DIR && sudo -u www-data php artisan migrate"
echo ""
echo -e "  3. Seed database (if needed):"
echo -e "     sudo -u www-data php artisan db:seed"
echo ""
echo -e "  4. If you update code later:"
echo -e "     cd $APP_DIR && git pull"
echo -e "     sudo -u www-data composer install --no-dev"
echo -e "     sudo -u www-data php artisan migrate --force"
echo -e "     sudo -u www-data php artisan optimize"
echo ""
echo -e "  ${BOLD}Nginx logs:${NC}"
echo -e "    tail -f /var/log/nginx/ahpc.error.log"
echo -e "    tail -f /var/log/nginx/ahpc.access.log"
echo ""
