<?php

namespace App\Support;

enum SubscriptionAmount
{
    public const  BASIC_SCHOOL_PER_STUDENT_PER_YEAR = 45;
    public const  BASIC_SCHOOL_PER_STUDENT_PER_HALF = 30;
    public const  BASIC_SCHOOL_PER_STUDENT_PER_QUARTER = 20;
    public const  SENIOR_SCHOOL_PER_STUDENT_PER_YEAR = 60;
    public const  SENIOR_SCHOOL_PER_STUDENT_PER_HALF = 45;
    public const  SENIOR_SCHOOL_PER_STUDENT_PER_QUARTER = 30;


    public const  BASIC_SCHOOL_INST_PER_STUDENT_PER_YEAR_ALL_SUBJECTS = 60;
    public const  BASIC_SCHOOL_INST_PER_STUDENT_PER_HALF_ALL_SUBJECTS = 45;
    public const  BASIC_SCHOOL_INST_PER_STUDENT_PER_QUARTER_ALL_SUBJECTS = 30;
    public const  BASIC_SCHOOL_INST_PER_STUDENT_MID_TERM_ONCE = 7; // per subject
    public const  BASIC_SCHOOL_INST_PER_STUDENT_MOCK_EXAMS_ONCE = 15; // per subject

    public const  SENIOR_SCHOOL_INST_PER_STUDENT_PER_YEAR_ALL_SUBJECTS = 90;
    public const  SENIOR_SCHOOL_INST_PER_STUDENT_PER_HALF_ALL_SUBJECTS = 60;
    public const  SENIOR_SCHOOL_INST_PER_STUDENT_PER_QUARTER_ALL_SUBJECTS = 35;
    public const  SENIOR_SCHOOL_INST_PER_STUDENT_MID_TERM_ONCE = 10;
    public const  SENIOR_SCHOOL_INST_PER_STUDENT_MOCK_EXAMS_ONCE = 20;

    public const  BASIC_SCHOOL_ONE_OFF = 10;
    public const  SENIOR_SCHOOL_ONE_OFF = 15;
    public const  UNIVERSITY_ONE_OFF = 20;
    public const UNIVERSITY_SCHOOL_PER_STUDENT_PER_YEAR = 35;
    public const UNIVERSITY_SCHOOL_PER_STUDENT_PER_HALF = 35;
    public const UNIVERSITY_SCHOOL_PER_STUDENT_PER_QUARTER = 35;

}
